apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: apgspace
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    command: ["false"]  # This command will immediately fail, causing a crash loop
